### ISSUE TITLE
Method '*' not found in [blank] for $this->object

### ISSUE THREAD

**Issue by ghost** [Haehnchen/idea-php-phpunit-plugin#11]
# Problem description
First off, thanks for improving the old PHPUnit plugin, it already works a lot better, but I noticed that `$this->object->method()` doesn't work. 

# Example PHP file
``` PHP
<?php
declare(strict_types=1);

use PHPUnit\Framework\TestCase;

class Test extends TestCase
{

    private $example;

    public function setUp()
    {
        $this->example = $this->prophesize(TestCase::class);
    }

    public function test()
    {
        $second_example = $this->prophesize(TestCase::class);

        $this->example->getAnnotations();
        $second_example->getAnnotations();
    }
}
```

# Screenshot:
![image](https://cloud.githubusercontent.com/assets/3717518/25897483/60a4eb5e-3588-11e7-95fb-a32365f663e8.png)
![image](https://cloud.githubusercontent.com/assets/3717518/25897511/79f710be-3588-11e7-8c5a-4f8089e6ddfc.png)

# Details
PhpStorm 2017.1.3
Build #PS-171.4424.11, built on April 26, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.13.0-106-generic

PHPUnit Enhanced
Version: 2.2

**Comment by Haehnchen** [comment]
already in
