### ISSUE TITLE
Prophecy Argument::any() must treat as any needed variable

### ISSUE THREAD

**Issue by dbalabka** [Haehnchen/idea-php-phpunit-plugin#12]
![image](https://cloud.githubusercontent.com/assets/1269372/25949691/1022183a-3661-11e7-9eff-83486feaa2c2.png)

**Comment by hipio** [comment]
@torinaki Was about to report this issue as well. This would reduce the pointless warnings in my IDE (when writing tests) by a lot.

**Comment by stof** [comment]
Actually, magic calls for Prophecy must accept any argument token (i.e. classes implementing `Prophecy\Argument\Token\TokenInterface`) in addition to the original type. AnyValueToken is not the only one causing issue.

**Comment by daniele-xp** [comment]
it is very annoying...
I'm using this phpstorm annotations to disable errors and warnings in that specific statement
```php
/** @noinspection PhpParamsInspection PhpStrictTypeCheckingInspection */
$this->calculatorMock
    ->add(Argument::cetera())
    ->willReturn(42);
```

**Comment by Haehnchen** [comment]
done
