### ISSUE TITLE
No autocomplete for test class field

### ISSUE THREAD

**Issue by overgapo** [Haehnchen/idea-php-phpunit-plugin#13]
```
class A {
    public function foo() {}
}

class FooTest extends \PHPUnit_Framework_TestCase
{
    /** @var A|ObjectProphecy */
    private $a;

    protected function setUp(): void
    {
        $this->a = $this->prophesize(A::class);
    }

    public function testFoo(): void
    {
        // $this->a->foo()-> no autocomplete

        $a = $this->prophesize(A::class);
        $a->foo()->shouldBeCalledTimes(1); // /ok
    }
}
```

**Comment by jonnywilliamson** [comment]
Just for info I have the same.

**Comment by hipio** [comment]
This works for me on the latest version (2.2.1).

![image](https://cloud.githubusercontent.com/assets/3717518/26682576/3c166a8c-46e1-11e7-842d-41e438b9b299.png)

**Comment by overgapo** [comment]
@hipio, try to get autocomplete for `->shouldBeCalledTimes(1)` method after `$this->example->bar()`

**Comment by hipio** [comment]
@overgapo You are correct, it does indeed not work, I retract my statement.

**Comment by scheb** [comment]
Any update on this? I'm using plugin version 2.7 on PhpStorm 2017.2.4 and I have the same behavior that @overgapo showed above. Sadly this makes Prophecy quite hard to use when you want to create the unit-under-test and the mocks in the setUp method.

**Comment by AlesZurek** [comment]
Any update on this issue?
I have got the same problem.
I am storing mock to class property in setUp method like this

**Comment by Haehnchen** [comment]
![image](https://user-images.githubusercontent.com/1011712/80233960-9ba85b00-8657-11ea-9621-96e0883cb230.png)

tested and working
