### ISSUE TITLE
Add action "Create test for class"

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-phpunit-plugin#22]
It would be nice navigate to class name, then press `alt+ins` or `alt+enter` and choose something like "Create test for class".

Relates to #16

**Comment by King2500** [comment]
I think PhpStorm already has such action built-in

**Comment by Koc** [comment]
cann't find it. Could you give hotkey combination and screen please?

**Comment by King2500** [comment]
https://confluence.jetbrains.com/plugins/servlet/mobile#content/view/51189191

**Comment by Koc** [comment]
Shipped with PHPUnit action not useful: we need always define correct namespace for test and path for target class file.

**Comment by Haehnchen** [comment]
i guess we dont need such feature here. PhpStorm looks fine to me, if test folders are marked:

![image](https://user-images.githubusercontent.com/1011712/80248453-3a40b600-8670-11ea-8bc0-a51092d0618a.png)

**Comment by Koc** [comment]
yes, issue is not relevant anymore.
