### ISSUE TITLE
expectedException annotation suggests all classes

### ISSUE THREAD

**Issue by Koc** [Haehnchen/idea-php-phpunit-plugin#23]
Not 100% sure that `@expectedException` feature added by this plugin, but cann't find any other plugin in my env that could add it.

As you see from screen: all of classes completed. Instead of this we can suggest only subchild of `\Throwable`.

![default](https://user-images.githubusercontent.com/191082/29003282-9295f008-7abc-11e7-9a21-6167f576fb79.png)

**Comment by Haehnchen** [comment]
PhpStorm improvements. external issue: https://youtrack.jetbrains.com/issue/WI-38286
