### ISSUE TITLE
gutter button that runs tests executes tham in debug mode 

### ISSUE THREAD

**Issue by Gamesh** [Haehnchen/idea-php-phpunit-plugin#32]
the gutter run button implemented in #4 exeutes tests in debug  mode, which enables xdebug 
running test by default in debug mode is not desirable, because it enables xdebug and that causes slow downs.
can we switch to regular run of tests ?

**Comment by istepaniuk** [comment]
I have the same problem. There does not seem to be a way to change it. The gutter button even says "Run Test"  in its tooltip, but then runs in debug mode.

**Comment by Gamesh** [comment]
Actually it doesn't matter phpstorm 2018 will have this built in, and you can choose in which mode you would like to run tests https://blog.jetbrains.com/phpstorm/2018/01/phpstorm-2018-1-eap-181-3263-18/
might cause conflict with this plugin though
