### ISSUE TITLE
Disable gutter icons starting from PhpStorm 2018.1

### ISSUE THREAD

**Issue by wbars** [Haehnchen/idea-php-phpunit-plugin#33]
Hello!

We are going to implement gutter icons for the PHPUnit tests as part of [this ticket](https://youtrack.jetbrains.com/issue/WI-15425), so you may consider to disable your implementation starting from ticket fix version (which will be one of the 2018.1 EAP versions).

**Comment by scaytrase** [comment]
Yes, really annoying since release, but disabling plugin gets more drawbaks, so we have to deal with to two arrows working differently

**Comment by mekras** [comment]
I am using both icons because native PHPStorm icon creates new run configuration, and plugin icon runs test without creating configuration. It is handy when you just want to be sure that some test is not broken.

**Comment by King2500** [comment]
The native one should provide both possibilities:

Left click: run directly.
Right click: show menu with different run options (normal, debug, coverage) and create appropriate run config.

**Comment by wbars** [comment]
@mekras Hi, could you please elaborate why creating new run configuration while running the test is bad thing? It will be not persisted if you don't want to and it will be vanished when number of tmp configurations will surpass the threshold.

**Comment by mekras** [comment]
> It will be not persisted if you don't want

Currently it will be persisted. And worse, when switching between tasks, it can fall into the configuration lists in other tasks. Now I have to delete these configurations manually. The idea-php-phpunit-plugin implementation lacks these drawbacks.

**Comment by mekras** [comment]
@wbars,

 > It will be not persisted if you don't want

Currently it will be persisted. And worse, when switching between tasks, it can fall into the configuration lists in other tasks. Now I have to delete these configurations manually. The idea-php-phpunit-plugin implementation lacks these drawbacks.

**Comment by Haehnchen** [comment]
feature removed from plugin
