### ISSUE TITLE
Allow to configure "constructor" (setUp) method

### ISSUE THREAD

**Issue by mdio** [Haehnchen/idea-php-phpunit-plugin#35]
Hi.

While using the plugin in conjunction with Prophecy I noticed that prophesizing local variables works (autocompletion and all) but for class properties it doesn't.
I traced it down to [src/de/espend/idea/php/phpunit/utils/ChainVisitorUtil.java#L102](https://github.com/Haehnchen/idea-php-phpunit-plugin/blob/master/src/de/espend/idea/php/phpunit/utils/ChainVisitorUtil.java#L102).

Since we've made TestCase::setUp() final and provide setUpBeforeTest instead so that people won't fail into the trap of forgetting to call parent::setUp(), this hardcoding prevents us from having Prophecy work with class properties.

It would be awesome for us to have this string configurable so we could put in setUpBeforeTest instead.

Right now the plugin exposes no settings at all (as far as I can tell) and I could totally understand if you'd like to keep it that way because that options screen would mean more maintenance burden.
But maybe an optional file in the project root (like the `dynamicReturnTypeMeta.json` of the [DynamicReturnTypePlugin](https://github.com/pbyrne84/DynamicReturnTypePlugin)) in the simplest of formats would be okay for you?
That would also make it even easier for us to use because every developer would only need to install plugin and the configuration would come with the repository.

Thank you for maintaining the plugin! Because without it, Prophecy's usefulness in conjunction with PhpStorm is greatly decreased.

**Comment by Haehnchen** [comment]
`setUpBeforeTest` added also this, i dont think that there much more use cases where a settings is needed
