### ISSUE TITLE
Autocomplete only works for "*Test" class?

### ISSUE THREAD

**Issue by icanhazstring** [Haehnchen/idea-php-phpunit-plugin#37]
Hi there,

i noticed something which i don't know is working as intended but i find it a little - weird to be honest.
The autocomplete for prophecy or mockobject only works if the class ends on Test.

As seen on this screenshots:
![image](https://user-images.githubusercontent.com/883543/45084591-feee1e00-b0fe-11e8-809e-9997f0aefa25.png)

![image](https://user-images.githubusercontent.com/883543/45084609-0b727680-b0ff-11e8-9800-86418ff88d7e.png)

Can't this be working if either:
- Class ends on Test
- Method has the `@test` annotation
- Method starts with test_ or ends with Test
- Class extends `PHPUnit\TestCase`

**Comment by CiderAndWhisky** [comment]
I would prefer if it also works if the class is derived from TestCase, because I use Prophecy inside Gherkin Feature Contexts that are not Standard PhpUnit tests.

**Comment by Haehnchen** [comment]
@CiderAndWhisky @icanhazstring there is a way to check for use statements. What is behind "TestCase" indetail that i can whitelist it. still the phpunit implementation?

**Comment by CiderAndWhisky** [comment]
@see http://ffishnc.reifinger.de/integration-tests-mit-guerkchen-teil-2/ (German language)

Basically, it is something like this:
```class FooContext extends \PHPUnit\Framework\TestCase implements \Behat\Behat\Context\Context```

Inside this class, Prophecy is not recognized, as the class is not named FooTest.

**Comment by Haehnchen** [comment]
extened the test detection, hopefully it somehow matches now ;)

**Comment by CiderAndWhisky** [comment]
Nais, so we don't have to call the classes "SomethingFeatureContextTest" any more :-D

**Comment by icanhazstring** [comment]
Nice. Thank you ❤️
