### ISSUE TITLE
Autocomplete not working in closures

### ISSUE THREAD

**Issue by icanhazstring** [Haehnchen/idea-php-phpunit-plugin#38]
Hi there,

i noticed the autocomplete for prophecy and mockobjects are not working in closures.

As seen here:
![image](https://user-images.githubusercontent.com/883543/45085858-0531c980-b102-11e8-8537-0ecb7c26ab11.png)

For easy copy paste:
```
$class = $this->prophesize(\Exception::class);
$class->getLine()->shouldBeCalled();

$closure = function() use ($class) {
    $class->getLine()->
};
```

**Comment by Haehnchen** [comment]
working now
