### ISSUE TITLE
Autocomplete in PHPUnit method method stopped working

### ISSUE THREAD

**Issue by digibeuk** [Haehnchen/idea-php-phpunit-plugin#39]
In the past it was possible to have autocompletion in the  `\PHPUnit\Framework\MockObject\Builder\InvocationMocker::method` method, i've tested this with version 3.7 en 3.8, but it does not work anymore.

For instance in this example below would expect `getCurrentRequest` to get type hinted. Also refactoring > rename command from PHPStorm would rename these occurences in the past which was very handy.

![carbon](https://user-images.githubusercontent.com/5148394/47563875-754f1580-d923-11e8-9f25-cc207fe8da2f.png)

I saw you have an unreleased commit in master which I suspect could solve the problem

**Comment by davidkmenta** [comment]
It seems that it works (at least the autocompletion) when you omit the "expects" method call. Tested with PHPUnit 8, phpStorm 2019.1 and PHPUnit Enhancement 3.8.

Sure, it's not handy, but better than nothing 😊

**Comment by digibeuk** [comment]
> It seems that it works (at least the autocompletion) when you omit the "expects" method call. Tested with PHPUnit 8, phpStorm 2019.1 and PHPUnit Enhancement 3.8.
> 
> Sure, it's not handy, but better than nothing

Ha :smile: 

But it really need the expectations

**Comment by Haehnchen** [comment]
looks now to be working:

![image](https://user-images.githubusercontent.com/1011712/79636871-45c94400-817b-11ea-9834-68c436cdc6a8.png)

**Comment by digibeuk** [comment]
work again! Thanks very much this is a great time-saver for me!
