### ISSUE TITLE
Autocompletion does not work for PHPUnit 8

### ISSUE THREAD

**Issue by someniatko** [Haehnchen/idea-php-phpunit-plugin#42]
Probably related to #39

**Comment by Haehnchen** [comment]
Tested with PhpStorm `2020.1` and phpunit 8.5. Found only one interface which i added, but was needed. But also fixed alot of other issues. Please valid in next release, if you still able to do so.

```
    "require": {
        "phpunit/phpunit": "^8.0"
    },
```
