### ISSUE TITLE
Add support for phpspec/prophecy-phpunit

### ISSUE THREAD

**Issue by acelaya** [Haehnchen/idea-php-phpunit-plugin#46]
PhpUnit 9.1 has deprecated the `prophesized` method from `TestCase` class, and recommends installing the phpspec/prophecy-phpunit package, which includes a trait which brings back this method.

However, when using `prophesize` from the trait, idea-php-phpunit-plugin no longer detects the mocked type, and you loose the intellisense and method autocompletion.

**Comment by Haehnchen** [comment]
added support for this new trait based on phpunit 9.1
