### ISSUE TITLE
Restric types after assertion

### ISSUE THREAD

**Issue by Jean85** [Haehnchen/idea-php-phpunit-plugin#53]
I'm using static analysis (PHPStan, Psalm) on my tests, and with the appropriate extensions they are able to restrict types after I've applied assertions.

```php
$this->assertIsString($foo);
// $foo is string now

$this->assertIsInstanceOf(Bar::class, $foo);
// $foo is a Bar instance
```

Would it be possible to do the same here? It would enable autocomplete os such variables, and suppress warning due to unknown types.

**Comment by Haehnchen** [comment]
its not related to this plugin, the methods having the docblock describing the behavior.

https://github.com/Haehnchen/idea-php-generics-plugin you can look at this plugin; some docblock are already support.

**Comment by King2500** [comment]
> its not related to this plugin, the methods having the docblock describing the behavior.

How can you add PhpDoc yourself to methods for PHPUnit?

**Comment by Haehnchen** [comment]
PHPUnit is already having the docblock: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Assert.php#L1324

**Comment by Jean85** [comment]
Thank you!
