### ISSUE TITLE
Add magic Prophecy method

### ISSUE THREAD

**Issue by Haehnchen** [Haehnchen/idea-php-phpunit-plugin#8]
`prophesize` method also returns `Prophecy\\Prophecy\\ObjectProphecy` and `Prophecy\\Prophecy\\MethodProphecy`

```
$foo = $this->prophesize(MYFOO::class);
$foo->find()->willReturn(true); # MISSING willReturn
```

https://github.com/maxfilatov/phpuaca/issues/27
https://github.com/maxfilatov/phpuaca/issues/28

**Comment by King2500** [comment]
Remember https://github.com/maxfilatov/phpuaca/pull/7

**Comment by King2500** [comment]
Does `$foo->reveal()` return the original target type (`MYFOO` in your case)?
(Maybe separate issue?)

**Comment by Haehnchen** [comment]
thx, opened new issue for `reveal` support

**Comment by Haehnchen** [comment]
done
